### ISSUE TITLE
TS 5.4.2 breaks `ConditionalKeys` and `SetParameterType`

### ISSUE THREAD

**Issue by trevorade** [sindresorhus/type-fest#831]
For `ConditionalKeys`, the root issue is: https://github.com/microsoft/TypeScript/issues/56644 which sound slike it will not be fixed. Basically, the `NonNullable` call in the `ConditionalKeys` type is ignored and does not run. Based on that issue, it's possible this type can be rewritten to be compatible with 5.4.2 but I'm unclear exactly on how...

I haven't debugged `SetParameterType` very closely but I just noticed that it too has issues in TS 5.4.2

**Comment by voxpelli** [comment]
How come the canary is not picking up on this? https://github.com/sindresorhus/type-fest/actions/workflows/ts-canary.yml

**Comment by voxpelli** [comment]
@trevorade Extending the tests to highlight this failure would be a good first step I think 👍 

This is the second breakage in the 5.4-line, after https://github.com/sindresorhus/type-fest/issues/784

**Comment by trevorade** [comment]
Hey @voxpelli, we were just updating our code repository in my company to 5.4.2 and this test started breaking so I figured I would send an early signal. I'm not really looking for contribution opportunities at the moment.

Here's the [`ConditionalKeys` test](https://github.com/sindresorhus/type-fest/blob/main/test-d/conditional-keys.ts) rewritten in TS Playground: [link](https://www.typescriptlang.org/play?ts=5.4.2#code/PTAEBUE8AcFNQEYEMDOsAmoD2A7AXAFAigAWALmdCniAOYCWZJArggHQDGWAtsCvTnQAnWCixCWKYGRiwAtADNRZYAgA2WBMG5IBfLMyEdYwLoMb1cSNXIDWsSCjbo2ZFAQIy4oAMK50FlZqANIOKAAKSEJkAIwAPABCqLAANL7+gTgAfKAAvKAAcrgFzGpqSOqwcX7mZJY41qGOkdEATInJaTUBdbhZWQDcHl7w3ZmNYS1k7UloXRm92XmgAN4EoKAA2k2gAqD2kFgKoLOwALp4J8nbDmegsAAeZLCCKOm19aAA-KA7lziwABusCEQwAvpsDkcrmgzkNPLJQABRB5IbjQNTwfJrACQSEuKDIQgEtCGOIQXwJRJJoAAPqAcMxuAgQWSOJTQITiThSQQcehLgAlWBcIToOJcklpZg4Ww4LAAd2y4PhxAAyiQDGpMCzQAAiJB6tigADqQlwtF2OFAAFY2AAWNitY0m8S2N57O0AZjYXoIK1AI1AIhQpTIyzGiwmzSisTiKLRGNSnOpPMGoDBRDAGw2AD0vh5iK6hO7dsdDsxQAERBwyGpIKAONY1IViqVypVsMw3PR0PAkKBaC8QfQOIHZGx-ePvCGw8sijgSmUKpjqgt6tGIrH2gn0Zi0pK0+nM8Qc6B8x4s6ANVqdfAAAYGvV0-UcPX3l3mnlW20Op0ut0PWtb1fSnINZzUcN8kjDcQkmWN4l3JMD1TS16RlPsFAEDBjyvM8LyvYtS3ocsDCregazrBsmzKVtF3bFd4AMHs+1AAchwBYkxxGScA3A0Q53yBclw7VcYKCJotzaeNUT3ZNDzQ0AMNgLCAXQfoBgzPCcwvIA) (change the version to "5.3.3" to see the old behavior)

**Comment by shicks** [comment]
> How come the canary is not picking up on this? https://github.com/sindresorhus/type-fest/actions/workflows/ts-canary.yml

We don't use `tsd` in our internal fork, but have (programmatically) rewritten the tests to use a simpler typechecking assertion library.  My guess about why your CI workflow didn't pick up the breakage is that it was using `tsd` for type checking, which has its own version of typescript built into it - so it's still effectively testing against the old version.  (FWIW, this is the main reason we don't use `tsd` - we want a single typescript import to control all type checking everywhere).

**Comment by trevorade** [comment]
For `ConditionalKeys`, looks like the fix is to just add `-?`:

```
export type ConditionalKeys<Base, Condition> = NonNullable<
// Wrap in `NonNullable` to strip away the `undefined` type from the produced union.
{
  // Map through all the keys of the given base type.
  [Key in keyof Base]-?:
  // Pick only keys with types extending the given `Condition` type.
  Base[Key] extends Condition
  // Retain this key since the condition passes.
    ? Key
  // Discard this key since the condition fails.
    : never;

  // Convert the produced object into a union type of the keys which passed the conditional test.
}[keyof Base]
>;
```

Fixes the tests on our end anyways.

**Comment by trevorade** [comment]
Here's some debugging info for `SerParameterType`. Specifically, the issue appears to be with `MergeObjectToTuple`:

[TS Playground link](https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAshBOBzCB5ARgKwgY2AFQHs8BXMAGwgB4TzoIAPYCAOwBMBnKY5ga2YIDuzANoBdADRQASjgLxWAfSgMmbTjOxzWlZsQC2aBJO59BzAHzmoAXigBvAFBQowgNJQAlsyg8IIAgBmUDQUogBc0rLySiosHJGa8pTswPBeiMa8-ELmTs5QAPQFUAASAIZsFFAEmDjAUNhl7NBkHr5QAAZ2AAwRKWnMGVAAjBG6BggAvh15zgD8UO6xap0AJHZeAQhQAHL6hvBLjHGc4wfTs-kLexOHyscrvv5BGlpKC6-RbqJQESEQ30uzjGEAAbghLkVShVWFVgKQqo1mlBWu0OsJ+ulJGcEKIZvlfot7qp4k9Agk3lAPlFFN9Cf9AZMANwOBx2UCQKBMFI2WAIZDoLC4Qj-SjCMpjfZGKAAOjlaD6IAMBDIYgk9km5kmDih+QAenNWezwNBufVbHAkKhasKiAiqOLJbdJHKZQqoOwlWgVWrJD0+ql0prtbrnAajRzTRAeRb+dahfg7bQxRKoDj4C75YrlarROqxFqdcV9Ya2ZGudHzXyrYK6iL7SmnQdM27s97c-nMYNRIXQ1Bw2WTRWY9WBTbE6LHWmpRnZVmPV6fXnJBjA4MW+m1b3i2HDUA) (change the version to 5.3.3 to see the difference)

This one may indicate a TypeScript bug

**Comment by Emiyaaaaa** [comment]
Hi @trevorade 

I did some test, If we focus only on the results of type `A`, it looks like 5.4.2 is correct?

```tsx
type Test<Tuple extends unknown[]> = {
	[K in keyof Tuple]: K
};

type A = Test<[a: number, b: string, c: Object, ...arguments: boolean[]]>
// v5.3.3 type A = [a: "0", b: "1", c: "2", ...arguments: "3"[]]
// v5.4.2 type A = [a: "0", b: "1", c: "2", ...arguments: number[]]
```

[Playground Link](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAKhDOwA8MCuYA20IA9gQDsATeKVAgawIHsB3AgbQF0A+KAXigG8AoASAYBpKAEsCUChBDUAZrHRYmALiiCeAXwDcPHqEhQAgh1gJkDAIYqCqALYAjCACcANFDsrEjsQHNXAYxUAeTsAKwg-YFcAOhiAfXNHb1tCYHgVO2pqLHNGJlYeAHoCqAA3AFYogGYqqD1oI04LFQAiAAZm13coZoBGDqgA7oAmfpio+MTkglSWyubmJkLi8qiAFiih2vB64ybu9s6Wvv8Wkei4hKSbFLSoa3snBZ4gA)

**Comment by sindresorhus** [comment]
`SetParameterType` should be fixed in https://github.com/sindresorhus/type-fest/releases/tag/v4.13.0

**Comment by trevorade** [comment]
Thanks. I'll verify the fix on our end later today

**Comment by trevorade** [comment]
Confirmed on our end that `SetParameterType` is fixed. Thx!

`ConditionalKeys` should be easy to fix:
https://github.com/sindresorhus/type-fest/issues/831#issuecomment-1995932047

**Comment by trevorade** [comment]
Apologies, `SetParameterType` is not quite fixed.

For this case in tsc 5.4.2:

```typescript
// Test another define way
declare const test3: SetParameterType<typeof fn, [a: string, b: boolean]>;
expectType<(a: string, b: boolean, c: Object, ...args: boolean[]) => null>(test3);
test3('1', true, {}, true);
```

I'm seeing the type of `test3` resolve to: 

```typescript
type test3Type = (_a: string, _b: boolean, _c: Object, ..._arguments: (string | boolean)[]) => null
```

You can ignore the difference in parameter names but the last rest parameter is resolving to `(string | boolean)[]` rather than the expected `boolean[]`.

[Here's a reproduction of this error in TS Playground.](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSBnAcgVwDZ4A8AKgHxwC8cA2sQLpygzAB2AJhjS-ngwPwIoOVAC44AMwCGeDMADcAKAWhIsBMlSYAqiwDWLCAHcWJclQAUCgJA49B44xDN2nYtasDMuAqcfOOEtKy7h6CwiFiUjLA7pFBMQCUisrg0PBIKHAAyjCSMACWAMYACpKwAPLiAIJQUJKIJH6sATr6Riw1dYgANHAASsAY+PBMzZyt9h219ZQ0dGbWxE0ucLZtxu4C3AC2AEbAUMsBxNQA5HisAOYwABan-CFLoytQwJJsECx4iDT5LOIHOBaXoAOjBfwBhwAanQQqEcnkiqUKtVpg0ob1qGCQQMhngYL0tPM4WJccMInA3FYrGIWMAAG4HZIqNLqTITdqdGZUV7vT7fVZ2drUOjJDKoACyB0uwHKuwAVsBCjBiBAuQ1iOqjuMhcZ1b1iHLFcqDeqAMIQMA-Z4tXVTLqzTVohZWQ0KpUjJxjIF29WbOA7faHG2uI0es4XFjXO6w6mhN3GmAUgDecOoAGk4H84LpgIgIOJKeq6GJMyGc3mC5Sw8q4AIE+H0wwxE6uhnY9SAL6xavu2vliB9pNxgSpuNWDNZlgV-OF1v1EtwstelYAAwAJMmIYDcHsDsv-JxAwdO6u4aFd0GD97c7Pe4m6-fw5f982i2j2+faTg98GVwF03PeFcgKEoyhgSp1RIc1LUQUgIyuW57m1GcqwbZUgPjGsYGoBFQORCDUS6aC0QtK14PORCYw7ccaXfNsmyA2kGQOEJOzgZjGSgZlUjUcVsmAGBkUkbZBIOYgNEIAAxady3MbEykuH9WBgDAAH0xEkFhEBFBJKHINZJl6YoUIGQpoDYQhjygXpDPaUgXRklDzFufIMDEbdDmIG43JqS5QTBRTlJYVSNKnSE4D84LVL0igDLtf1LDjbQ7RIHyMD88hyxgIQYnHAR5MCqAlNEkL1LEKVitlIdVSgqLStU4zSFi8gBhgHAoBYCSUGklhSBJOAXPSlt0r8gKQSChryrgSqZWw2q0UIeqVIwJqWv6QSOq6ySZP66kEh7GTknEWxlXyT4JBYcw1Mkb9f16NTdjEDAcr+fy4DUwoxGw8abuK6L3LgXYIAgC4tN0uAx1edrOoDHhFG7BQTpYM6LvEFgAHV8luby3KGtyxCx9gjAe264d-PSoc22HuAIBGlHMlgXrgMooCMKTToKC6LBuu6g3W2m8GSAB6YW4CwaBtmkOBCkkWRBsAUHI4FKDAMDeg62CVPAylQRnmeYF6AEYxCyQThNE5goG64BCHFKt0d6ZNjaBkGwZYTtSEUUXHBQZVrcIcwyes3onpd0G3hYXovrgH64AU4rAeB8PwboAWeFIFzBhgQ2kgUA3s-MQ3ehy4RHc7YvctzhRveILO4G2YZ8jAC44DAMoRLEqBOHMJWVbVqMNa1nWZc+fWs4AJhNs324t8TJLtwsHchgAGZ7XqjOQ4EnsO3Y9r2xZUD1-cDteoDekPT-PmWxCTt3xsUxPXYjiG4rhggM-z8fc8-8xTkN05einHHgAsIwAK7CCrjXOuWkIC3EBJrcQfxUCGBmOYQAMuRwCkpIfIeB1bVzFgACXKFCAAon0OABCyEkLgIAPg3ADBO-QxhdCFCa0KNrV4I8mbpCzgAZinkJGend-YL0upiMmL0z5RgvjvCO8x94+yPpJE+cAJFX1DrfCOUdvpDnvgnG+T8U5p3fpnF6PDv68N-v-cBYDIbl1AZAsWtdmarnjpcDAq5W6CMtorZWct+6XEHmw4eetuEvQfvw82Qj54aHtpHSGfCVHr0uHvfBCi-ZKKDj+IM0jVFSOvjHHRccipuMvlGF+5BBYfyzg-cxYSE6F0AVY2xjTTgOJ8X3PBrD2G61HqE3ICdt6mwEXUWeVtokoFiZiXJ71g7k2yUUkEGiU5yNSYfdJPVlHTOkbM6OszXGP2Tiwcpb88BVLqW4r+ih84P3HpYkBRc4APJLsANpTj4CsyMBITm51pw918arTpQ8OEhIQFnAArBErxc8eoiI+YYDmKMuZxOTKvRJkjkme1WeARRGzxFJKMackxMAwWvLrnAr5iKfkIBuHkOANLOCrlcu4zxIzO7tL8YCoJwLemgperjQGQzImW2ETExemNsY3H5Y7VF0yUnezWSqJRTLCZ-A+IYXoeL0UErOSqdKtTdVuRBLLAg5hDCqpJnAP+rTFBAA)

**Comment by Emiyaaaaa** [comment]
> Apologies, `SetParameterType` is not quite fixed.
> 
> For this case in tsc 5.4.2:
> 
> ```ts
> // Test another define way
> declare const test3: SetParameterType<typeof fn, [a: string, b: boolean]>;
> expectType<(a: string, b: boolean, c: Object, ...args: boolean[]) => null>(test3);
> test3('1', true, {}, true);
> ```
> 
> I'm seeing the type of `test3` resolve to:
> 
> ```ts
> type test3Type = (_a: string, _b: boolean, _c: Object, ..._arguments: (string | boolean)[]) => null
> ```
> 
> You can ignore the difference in parameter names but the last rest parameter is resolving to `(string | boolean)[]` rather than the expected `boolean[]`.
> 
> [Here's a reproduction of this error in TS Playground.](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSBnAcgVwDZ4A8AKgHxwC8cA2sQLpygzAB2AJhjS-ngwPwIoOVAC44AMwCGeDMADcAKAWhIsBMlSYAqiwDWLCAHcWJclQAUCgJA49B44xDN2nYtasDMuAqcfOOEtKy7h6CwiFiUjLA7pFBMQCUisrg0PBIKHAAyjCSMACWAMYACpKwAPLiAIJQUJKIJH6sATr6Riw1dYgANHAASsAY+PBMzZyt9h219ZQ0dGbWxE0ucLZtxu4C3AC2AEbAUMsBxNQA5HisAOYwABan-CFLoytQwJJsECx4iDT5LOIHOBaXoAOjBfwBhwAanQQqEcnkiqUKtVpg0ob1qGCQQMhngYL0tPM4WJccMInA3FYrGIWMAAG4HZIqNLqTITdqdGZUV7vT7fVZ2drUOjJDKoACyB0uwHKuwAVsBCjBiBAuQ1iOqjuMhcZ1b1iHLFcqDeqAMIQMA-Z4tXVTLqzTVohZWQ0KpUjJxjIF29WbOA7faHG2uI0es4XFjXO6w6mhN3GmAUgDecOoAGk4H84LpgIgIOJKeq6GJMyGc3mC5Sw8q4AIE+H0wwxE6uhnY9SAL6xavu2vliB9pNxgSpuNWDNZlgV-OF1v1EtwstelYAAwAJMmIYDcHsDsv-JxAwdO6u4aFd0GD97c7Pe4m6-fw5f982i2j2+faTg98GVwF03PeFcgKEoyhgSp1RIc1LUQUgIyuW57m1GcqwbZUgPjGsYGoBFQORCDUS6aC0QtK14PORCYw7ccaXfNsmyA2kGQOEJOzgZjGSgZlUjUcVsmAGBkUkbZBIOYgNEIAAxady3MbEykuH9WBgDAAH0xEkFhEBFBJKHINZJl6YoUIGQpoDYQhjygXpDPaUgXRklDzFufIMDEbdDmIG43JqS5QTBRTlJYVSNKnSE4D84LVL0igDLtf1LDjbQ7RIHyMD88hyxgIQYnHAR5MCqAlNEkL1LEKVitlIdVSgqLStU4zSFi8gBhgHAoBYCSUGklhSBJOAXPSlt0r8gKQSChryrgSqZWw2q0UIeqVIwJqWv6QSOq6ySZP66kEh7GTknEWxlXyT4JBYcw1Mkb9f16NTdjEDAcr+fy4DUwoxGw8abuK6L3LgXYIAgC4tN0uAx1edrOoDHhFG7BQTpYM6LvEFgAHV8luby3KGtyxCx9gjAe264d-PSoc22HuAIBGlHMlgXrgMooCMKTToKC6LBuu6g3W2m8GSAB6YW4CwaBtmkOBCkkWRBsAUHI4FKDAMDeg62CVPAylQRnmeYF6AEYxCyQThNE5goG64BCHFKt0d6ZNjaBkGwZYTtSEUUXHBQZVrcIcwyes3onpd0G3hYXovrgH64AU4rAeB8PwboAWeFIFzBhgQ2kgUA3s-MQ3ehy4RHc7YvctzhRveILO4G2YZ8jAC44DAMoRLEqBOHMJWVbVqMNa1nWZc+fWs4AJhNs324t8TJLtwsHchgAGZ7XqjOQ4EnsO3Y9r2xZUD1-cDteoDekPT-PmWxCTt3xsUxPXYjiG4rhggM-z8fc8-8xTkN05einHHgAsIwAK7CCrjXOuWkIC3EBJrcQfxUCGBmOYQAMuRwCkpIfIeB1bVzFgACXKFCAAon0OABCyEkLgIAPg3ADBO-QxhdCFCa0KNrV4I8mbpCzgAZinkJGend-YL0upiMmL0z5RgvjvCO8x94+yPpJE+cAJFX1DrfCOUdvpDnvgnG+T8U5p3fpnF6PDv68N-v-cBYDIbl1AZAsWtdmarnjpcDAq5W6CMtorZWct+6XEHmw4eetuEvQfvw82Qj54aHtpHSGfCVHr0uHvfBCi-ZKKDj+IM0jVFSOvjHHRccipuMvlGF+5BBYfyzg-cxYSE6F0AVY2xjTTgOJ8X3PBrD2G61HqE3ICdt6mwEXUWeVtokoFiZiXJ71g7k2yUUkEGiU5yNSYfdJPVlHTOkbM6OszXGP2Tiwcpb88BVLqW4r+ih84P3HpYkBRc4APJLsANpTj4CsyMBITm51pw918arTpQ8OEhIQFnAArBErxc8eoiI+YYDmKMuZxOTKvRJkjkme1WeARRGzxFJKMackxMAwWvLrnAr5iKfkIBuHkOANLOCrlcu4zxIzO7tL8YCoJwLemgperjQGQzImW2ETExemNsY3H5Y7VF0yUnezWSqJRTLCZ-A+IYXoeL0UErOSqdKtTdVuRBLLAg5hDCqpJnAP+rTFBAA)

Sorry, I made a mistake that ignore the number key when input is an array. I'm fixing it right now.

It seems that the improvement of the testing system is more urgent.

**Comment by sindresorhus** [comment]
> It seems that the improvement of the testing system is more urgent.

https://github.com/sindresorhus/type-fest/issues/837
